name: 微博每日签到打卡

on:
  workflow_dispatch:
  schedule:
     - cron: '5 0 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        WB_TOKEN: ${{ secrets.WB_TOKEN }}
        WB_COOKIE: ${{ secrets.WB_COOKIE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.WB_TOKEN
        run: |
          npm install
      - name: '运行 【新浪微博】'
        if: env.WB_TOKEN
        run: |
          node Task/weibo.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
